name: banhang
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  font_awesome_flutter: ^10.5.0

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_snake_navigationbar: ^0.6.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  scoped_model: ^2.0.0
  cached_network_image: ^3.2.0
  intl: ^0.18.1

  hive_flutter: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
